SELECT 
    "ARTICLES"."ID" as "ID",
    "ARTICLES"."TITLE" as "TITLE",
    "USERS"."ID" as "AUTHOR_ID",
    "USERS"."NAME" as "AUTHOR_NAME"
FROM
    "ARTICLES" JOIN "USERS" ON "ARTICLES"."AUTHOR_ID" = "USERS"."ID"
